/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Tue Feb  3 22:48:39 2026 */

/* parameterized module instance */
supervisorclk __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .CLKOS3( ), 
    .LOCK( ));
