/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Sat Dec 20 11:38:05 2025 */

/* parameterized module instance */
supervisorclk __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .LOCK( ));
