/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Tue Jan 27 14:01:57 2026 */

/* parameterized module instance */
supervisorclk __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .CLKOS3( ), 
    .LOCK( ));
