/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.0.396.4 */
/* Module Version: 5.7 */
/* Fri Dec 19 21:03:01 2025 */

/* parameterized module instance */
clocks __ (.CLKI( ), .CLKOP( ), .CLKOS( ));
