# we use printf from here
COMMON_DIR = ../../../fw/libsoc

MAIN_PRJ = Firmware
MAIN_SRC = helloworld.c

# Commandline options for each tool.

CFLAGS = -D_STACKSIZE=1024
LINKSCRIPT = $(COMMON_DIR)/stdrom.ld
include $(COMMON_DIR)/std_fast.mk

